/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as AdminSeriesIdRouteImport } from './routes/admin.series.$id'
import { Route as AdminTestIdRouteImport } from './routes/admin.test.$id'
import { Route as TestsIdIndexRouteImport } from './routes/tests_.$id.index'
import { Route as TestsIdAttemptRouteImport } from './routes/tests_.$id.attempt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeriesIdRoute = AdminSeriesIdRouteImport.update({
  id: '/series/$id',
  path: '/series/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestIdRoute = AdminTestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => AdminRoute,
} as any)
const TestsIdIndexRoute = TestsIdIndexRouteImport.update({
  id: '/tests_/$id/',
  path: '/tests/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIdAttemptRoute = TestsIdAttemptRouteImport.update({
  id: '/tests_/$id/attempt',
  path: '/tests/$id/attempt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/admin/series/$id': typeof AdminSeriesIdRoute
  '/admin/test/$id': typeof AdminTestIdRoute
  '/tests/$id/attempt': typeof TestsIdAttemptRoute
  '/tests/$id/': typeof TestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/tests': typeof TestsIndexRoute
  '/admin/series/$id': typeof AdminSeriesIdRoute
  '/admin/test/$id': typeof AdminTestIdRoute
  '/tests/$id/attempt': typeof TestsIdAttemptRoute
  '/tests/$id': typeof TestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/tests/': typeof TestsIndexRoute
  '/admin/series/$id': typeof AdminSeriesIdRoute
  '/admin/test/$id': typeof AdminTestIdRoute
  '/tests_/$id/attempt': typeof TestsIdAttemptRoute
  '/tests_/$id/': typeof TestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/tests/'
    | '/admin/series/$id'
    | '/admin/test/$id'
    | '/tests/$id/attempt'
    | '/tests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/tests'
    | '/admin/series/$id'
    | '/admin/test/$id'
    | '/tests/$id/attempt'
    | '/tests/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/tests/'
    | '/admin/series/$id'
    | '/admin/test/$id'
    | '/tests_/$id/attempt'
    | '/tests_/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  TestsIndexRoute: typeof TestsIndexRoute
  TestsIdAttemptRoute: typeof TestsIdAttemptRoute
  TestsIdIndexRoute: typeof TestsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/series/$id': {
      id: '/admin/series/$id'
      path: '/series/$id'
      fullPath: '/admin/series/$id'
      preLoaderRoute: typeof AdminSeriesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/test/$id': {
      id: '/admin/test/$id'
      path: '/test/$id'
      fullPath: '/admin/test/$id'
      preLoaderRoute: typeof AdminTestIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tests_/$id/': {
      id: '/tests_/$id/'
      path: '/tests/$id'
      fullPath: '/tests/$id/'
      preLoaderRoute: typeof TestsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests_/$id/attempt': {
      id: '/tests_/$id/attempt'
      path: '/tests/$id/attempt'
      fullPath: '/tests/$id/attempt'
      preLoaderRoute: typeof TestsIdAttemptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSeriesIdRoute: typeof AdminSeriesIdRoute
  AdminTestIdRoute: typeof AdminTestIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminSeriesIdRoute: AdminSeriesIdRoute,
  AdminTestIdRoute: AdminTestIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  TestsIndexRoute: TestsIndexRoute,
  TestsIdAttemptRoute: TestsIdAttemptRoute,
  TestsIdIndexRoute: TestsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
